core.symlinks=false
core.autocrlf=true
core.fscache=true
color.diff=auto
color.status=auto
color.branch=auto
color.interactive=true
help.format=html
rebase.autosquash=true
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
http.sslbackend=openssl
diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
credential.helper=manager
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=Alkaidek
user.email=35803025+Alkaidek@users.noreply.github.com
core.autocrlf=true
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
remote.origin.url=https://gitlab.com/Alkaidek/kreator-dyplomow.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
branch.v1.remote=origin
branch.v1.merge=refs/heads/v1
branch.v2.remote=origin
branch.v2.merge=refs/heads/v2
branch.v4.remote=origin
branch.v4.merge=refs/heads/v4
branch.v5.remote=origin
branch.v5.merge=refs/heads/v5
branch.v6.remote=origin
branch.v6.merge=refs/heads/v6
branch.v7.remote=origin
branch.v7.merge=refs/heads/v7
branch.v8.remote=origin
branch.v8.merge=refs/heads/v8
branch.v9.remote=origin
branch.v9.merge=refs/heads/v9
branch.v10.remote=origin
branch.v10.merge=refs/heads/v10
branch.v12.remote=origin
branch.v12.merge=refs/heads/v12
branch.v13.remote=origin
branch.v13.merge=refs/heads/v13
branch.v15.remote=origin
branch.v15.merge=refs/heads/v15
branch.v16MongoDB.remote=origin
branch.v16MongoDB.merge=refs/heads/v16MongoDB
branch.v17.remote=origin
branch.v17.merge=refs/heads/v17
branch.v18.remote=origin
branch.v18.merge=refs/heads/v18
branch.v20-Redis.remote=origin
branch.v20-Redis.merge=refs/heads/v20-Redis
branch.KD-version-2.0.remote=origin
branch.KD-version-2.0.merge=refs/heads/KD-version-2.0
