export const  appComponentStrings ={
  appComponentHello: 'Witamy w generatorze dyplomów',
  appComponentButton11: 'Tworzenie własnego',
  appComponentButton12: 'projektu dyplomu od podstaw',
  appComponentButton21: 'Tworzenie dyplomu',
  appComponentButton22: 'z gotowego projektu',
  appComponnentError1: 'Przepraszamy, ale strona nie może zostać załadowana!',
  appComponnentError2: 'Pamiętaj, aby najpierw zalogować sie na swoje konto Mac.pl.'

};
export const  createComponentStrings ={
  a1: 'Kreator dyplomów nie działa na małych ekranach!',
  a2: 'Jest to niezbędne dla zapewnienia najwyższej jakości doznań z użytkowania.',
  a3: 'Przepraszamy za kłopot',
  a4: 'WCZYTAJ SZABLON',
  a5: 'ZAPISZ SZABLON',
  a6: 'GENERUJ DYPLOM',
  a7: 'Wybierz orientację dyplomu',
  a8: 'Wybierz ilość podpisów',
  a9: 'Trzy podpisy',
  a10: 'Dwa podpisy',
  a11: 'krok',
  a12: 'krok',
  a13: 'Wybierz tło dyplomu',
  a14: 'Lustrzane odbicie w poziomie',
  a15: 'Lustrzane odbicie w pionie',
  a16: 'Kolor tła',
  a17: 'krok',
  a18: 'Wybierz ramkę dyplomu',
  a19: 'Usuń ramkę',
  a20: 'Usuń tło',
  a21: 'krok',
  a22: 'Wpisz dane',
  a23: 'Tytuł',
  a24: 'Uzupełnij pole',
  a25: 'Wielkość czcionki',
  a26: 'Kolor czcionki',
  a27: 'Czcionka',
  a28: 'Cień',
  a29: 'Kolor cienia',
  a30: 'Prawy margines',
  a31: 'Górny margines',
  a32: 'Odstęp między literami',
  a33: 'Dla kogo?',
  a34: 'Uzupełnij pole',
  a35: 'Lewy margines',
  a36: 'Za co?',
  a37: 'Podpisy',
  a38: 'Dolny margines',
  a39: 'Miejsce i data',
  a40: 'Dodatkowe Pole',
  a41: 'Pole opcjonalne',
  a42: 'krok',
  a43: 'Dodaj obrazek ze zbioru',
  a44: 'Emocje',
  a45: 'Obrazki z kategorii Emocje',
  a46: 'Geografia',
  a47: 'Obrazki z kategorii Geografia',
  a48: ' Literatura',
  a49: 'Obrazki z kategorii Literatura',
  a50: 'Matematyka',
  a51: 'Obrazki z kategorii Matematyka',
  a52: 'Muzyka',
  a53: 'Obrazki z kategorii Muzyka',
  a54: 'Polska',
  a55: 'Obrazki z kategorii Polska',
  a56: 'Rośliny',
  a57: 'Obrazki z kategorii Rosliny',
  a58: 'Sport',
  a59: 'Obrazki z kategorii Sport',
  a60: 'Święta',
  a61: 'Obrazki z kategorii Święta',
  a62: 'Szachy i Multimedia',
  a63: 'Obrazki z kategorii Szachy i Multimedia',
  a64: 'Zwierzęta',
  a65: 'Obrazki z kategorii Zwierzęta',
  a66: 'Dodaj swój obrazek',
  a67: 'Importuj obrazek',
  a68: 'Szerokość obrazka',
  a69: 'Zachowanie propocji',
  a70: 'Wysokość obrazka',
  a71: 'Górny margines obrazka',
  a72: 'Lewy margines obrazka',
  a73: 'Obrót obrazka',
  a74: 'Resetuj obrazek',
  a75: 'Usuń obrazek',
  a76: 'Resetuj obrót',
  a77: 'Domyślnie pliki szablonów znajdują zię w folderze Pobrane/Downloads',
  a78: 'Naciśnięcie spowoduje zapisanie stworzonego przez Ciebie szablonu. Plik zostanie zapisany w folderze Pobrane/Downloads',
  a79: 'Poprzedni krok',
  a80: 'Następny krok',
  a81: 'Naciśnij aby wybrać orientację poziomą',
  a82: 'Naciśnij aby wybrać orientację pionową',
  a83: 'Poprzednie tła',
  a84: 'Następne tła',
  a85: 'Naciśnij i wybierz kolor tła',
  a86: 'Poprzednie ramki',
  a87: 'Następne ramki',
  a88: 'Podpis 1\\n...............\\n',
  a89: 'Podpis 2\\n...............\\n',
  a90: 'Podpis 3\\n...............\\n',
  a91: 'Dyplom',
  a92: 'Twój szoblon został zapisany! Dodano go: ',
  a93: 'Nie udało się wczytać szablonu! Plik może być niepoprawny, uszkodzony lub niekompatybilny!',
  a94: 'Nie udało się wczytać szablonu! Plik może być niepoprawny, uszkodzony lub niekompatybilny!',
  a95: 'Plik jest za duży! Maksymalny rozmiar wynosi 2MB',
  a96: 'Nie udało się wczytać szablonu! Plik może być niepoprawny, uszkodzony lub niekompatybilny!',
  a97: 'Edytor obrazka znajduje się na dole strony!'
};

export const  templateComponentStrings ={
  a1: 'Kreator dyplomów nie działa na małych ekranach!',
  a2: 'Jest to niezbędne dla zapewnienia najwyższej jakości doznań z użytkowania.',
  a3: 'Przepraszamy za kłopot',
  a4: 'WCZYTAJ SZABLON',
  a5: 'Domyślnie pliki szablonów znajdują zię w folderze Pobrane/Downloads',
  a6: 'Naciśnięcie spowoduje zapisanie stworzonego przez Ciebie szablonu! Plik zostanie zapisany w folderze Pobrane/Downloads',
  a7: 'ZAPISZ SZABLON',
  a8: 'GENERUJ DYPLOM',
  a9: 'Następny krok',
  a10: 'Poprzedni krok',
  a11: 'Resetuj szablon',
  a12: 'krok',
  a13: 'krok',
  a14: 'Wpisz dane',
  a15: 'Pole',
  a16: 'Uzupełnij pole',
  a17: 'Wielkość czcionki',
  a18: 'Kolor czcionki',
  a19: 'Czcionka',
  a20: 'Cień',
  a21: 'Kolor cienia',
  a22: 'Górny margines',
  a23: 'Lewy margines',
  a24: 'Prawy margines',
  a25: 'Dodatkowe Pole',
  a26: 'Pole opcjonalne',
  a27: 'Wielkość czcionki',
  a28: 'Kolor czcionki',
  a29: 'Czcionka',
  a30: 'krok',
  a31: 'Dodaj obrazek ze zbioru',
  a32: 'Emocje',
  a33: 'Obrazki z kategorii Emocje',
  a34: 'Geografia',
  a35: 'Obrazki z kategorii Geografia',
  a36: 'Literatura',
  a37: 'Obrazki z kategorii Literatura',
  a38: 'Matematyka',
  a39: 'Obrazki z kategorii Matematyka',
  a40: 'Muzyka',
  a41: 'Obrazki z kategorii Muzyka',
  a42: 'Polska',
  a43: 'Obrazki z kategorii Polska',
  a44: 'Rośliny',
  a45: 'Obrazki z kategorii Rosliny',
  a46: 'Sport',
  a47: 'Obrazki z kategorii Sport',
  a48: 'Święta',
  a49: 'Obrazki z kategorii Święta',
  a50: 'Szachy i Multimedia',
  a51: 'Obrazki z kategorii Szachy i Multimedia',
  a52: 'Zwierzęta',
  a53: 'Obrazki z kategorii Zwierzęta',
  a54: 'Dodaj swój obrazek',
  a55: 'Importuj obrazek',
  a56: ' Obrazek nr.',
  a57: 'Szerokość obrazka',
  a58: 'Zachowanie propocji',
  a59: 'Wysokość obrazka',
  a60: 'Górny margines obrazka',
  a61: 'Lewy margines obrazka',
  a62: 'Obrót obrazka',
  a63: 'Resetuj obrazek',
  a64: 'Usuń obrazek',
  a65: 'Resetuj obrót',
  a66: 'Twój szoblon został zapisany! Dodano go: ',
  a67: 'Nie udało się wczytać szablonu! Plik może być niepoprawny, uszkodzony lub niekompatybilny!',
  a68: 'Edytor obrazka znajduje się na dole strony!',
  a69: 'Nie udało się wczytać szablonu! Plik może być niepoprawny, uszkodzony lub niekompatybilny!',
  a70: 'Plik jest za duży! Maksymalny rozmiar wynosi 2MB'
};

